"""Root README.md — the wiki front page."""

from __future__ import annotations

from jinja2 import Environment

_TEMPLATE = """\
{% if unpushed_commits %}
> ⚠ **WARNING:** {{ unpushed_commits }} commit(s) not pushed to remote.
> Run `serverdocs push` or use the `/push-docs` slash command in SilverBullet.

{% endif %}
# Server Documentation

Auto-generated documentation of VMs and containers across the fleet.

Below is a list of all configured servers and a note of how many Virtual Machines or
Docker continers have been discovered.

| Host | Entities | Last scan |
|---|---|---|
{% for h in hosts -%}
| [[servers/{{ h.host }}/INDEX|{{ h.host }}]] | {{ h.entity_count }} | {{ h.last_scan }} |
{% endfor %}

---

_Generated by [serverdocs](https://github.com/marlscot/serverdocs)._
"""


def render_front_page(
    hosts: list[dict[str, object]],
    *,
    unpushed_commits: int = 0,
) -> str:
    """Render the root README.md.

    ``hosts`` is a list of dicts with keys: host, entity_count, last_scan.
    """
    env = Environment(autoescape=False, keep_trailing_newline=True)
    return env.from_string(_TEMPLATE).render(hosts=hosts, unpushed_commits=unpushed_commits)
